# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "2-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_matrix:
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              TARGET: x86_64-unknown-linux
            - os: macos-latest
              TARGET: x86_64-apple-darwin
#            - os: windows-latest
#              TARGET: x86_64-unknown-windows
    runs-on: ${{ matrix.os }}
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/installed
        install-build: true
          
    - name: Capture installed folder
      shell: bash
      run: |
            tar -c -v -f webrtcsfu-${{ matrix.TARGET }}.tgz -z -C installed .

    - name: Upload installed folder
      uses: actions/upload-artifact@v3
      with:
        name: webrtcsfu-${{ matrix.TARGET }}.tgz
        path: webrtcsfu-${{ matrix.TARGET }}.tgz
        
