# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "2-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-matrix:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
          env: TRIPLET=x86_64-linux
        - windows-latest
          env: TRIPLET=x86_64-darwin
        - macos-latest
          env: TRIPLET=x86_64-windows
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/installed
        install-build: true
          
    - name: Capture installed folder
      shell: bash
      run: |
            tar -c -v -f webrtcsfu-${TRIPLET}.tgz -z -C installed .

    - name: Upload installed folder
      uses: actions/upload-artifact@v3
      with:
        name: webrtcsfu-${TRIPLET}.tgz
        path: webrtcsfu-${TRIPLET}.tgz
        
